### ISSUE TITLE
About shiny app YPRsim

### ISSUE THREAD

**Issue by lftorresc** [AdrianHordyk/LBSPR#13]
Dear Adrian,

in barefootecologist, what do you mean with parameters dL95 and dSL95 (Particullary what means the "d"). The codes in Rstudio didn't show what means.

Thanks

**Comment by AdrianHordyk** [comment]
dL95 is the increment between L50 and L95 - ie L50+dL95 = L95 (d stands for delta). It's done this way so that L95 is always > L50.

Same applies for dSL95.
