### ISSUE TITLE
Specifying SL50 and SL95 when fitting data

### ISSUE THREAD

**Issue by echelleburns** [AdrianHordyk/LBSPR#16]
Hi, I was wondering if it is possible to force the SL50 and SL95 outputs from `LBSPRfit()`, instead of having them estimated?

I tried adding SL50 and SL95 parameters to the `LB_pars` object before adding our length measurement data, but it seems that `LBSPRfit()` still estimates the SL50 and SL95 independently from the data.

**Comment by AdrianHordyk** [comment]
No, the model always estimates selectivity pattern from the data. One option is to estimate fishing mortality and selectivity parameters from the data, then take the estimate of F and apply your own selectivity curve in the simulation model to calculate the resulting SPR.

Also see this [paper](https://www.sciencedirect.com/science/article/pii/S0165783620300916?via%3Dihub) where the authors modified the model to allow a custom selectivity curve.
