### ISSUE TITLE
Specifying MLL and sdLegal

### ISSUE THREAD

**Issue by echelleburns** [AdrianHordyk/LBSPR#17]
When trying to specify MLL and sdLegal in the LB_pars parameter, I receive this error: 

`Error in ZKLMat[L - 1, ] : incorrect number of dimensions`

Code example below: 

```
MyPars <- new("LB_pars")
MyPars@Species <- "Red hind"
MyPars@Linf <- 54.6
MyPars@L50 <- 21.5
MyPars@L95 <- 28.5
MyPars@M <- 0.24
MyPars@MK <- 0.24/0.176
MyPars@L_units <- "cm"
MyPars@FM <- 0.87
MyPars@SL50 <- 35
MyPars@SL95 <- 36
MyPars@MLL <- 35
MyPars@sdLegal <- 1

MySim <- LBSPRsim(MyPars)
```

Removing the parameters for MLL and sdLegal results in no error and a reasonable SPR (~0.61). 

Am I specifying the MLL and sdLegal incorrectly?

**Comment by AdrianHordyk** [comment]
The problem is discard mortality for sublegal fish hasn't been set:
`MyPars@fDisc <- 0 # no discard mortality` should fix it

I'll add a check for this in future releases
