### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by yreecht** [AdrianHordyk/LBSPR#2]
Hi,
My first attempt to install the package (version 0.1.9000, commit 12849d3, R 3.3.2 64-bits on Windows) failed due to a missing 'colorspace' package.
Worked fine after installing it manually.
Yves

**Comment by AdrianHordyk** [comment]
Updated the Description and added the missing packages as dependencies.  Seems to have fixed the problem. Thanks for alerting me to this.

**Comment by yreecht** [comment]
You're welcome.
First tests are conclusive, the package seems great, thanks!
