### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by baibbat** [AdrianHordyk/LBSPR#5]
Dear

I try to run the LBSPR method to my data. but i find a little problem in the section 'Reading in Example CSV'

Actually, i couldn't read my csv file wich contain my data. so please can you help me in this case. i am sorry for this but i am a bigguner in R.

Thank you very much

**Comment by AdrianHordyk** [comment]
Happy to help. Please provide more details of the problem you are having, including a [reproducible example](https://gist.github.com/hadley/270442) if possible.

**Comment by baibbat** [comment]
thank you very much for reply my request. please find in attched file the script i used with the error and also my data.

thanks again

​






BAIBBAT Sid'Ahmed



Chef de Laboratoire des Pêches

Institut National de Recherche Halieutique/ C/R-DAKHLA
E-mail : baibat@hotmail.com<mailto:baibat@hotmail.com> ;

s.baibbat@gmail.com ;

baibbat@inrh.ma

Tel : 0661-64-25-73
________________________________
