### ISSUE TITLE
Small bug in LBSPR shiny

### ISSUE THREAD

**Issue by iagomosqueira** [AdrianHordyk/LBSPR#6]
Line 278 of https://github.com/AdrianHordyk/LBSPR/blob/master/inst/shiny_apps/LBSPR/server.r should say

```
 if (inherits(dat, "numeric") | inherits(dat,"integer")) {
```
as a comma is missing after `dat`. Sorry I cannot submit it as a pull request right now.

**Comment by AdrianHordyk** [comment]
Thanks for finding this. I'll push a fix to GitHub repo and will be updated in CRAN in next version release
