### ISSUE TITLE
Plot function behaviour is inconsistent

### ISSUE THREAD

**Issue by ahharvey** [AdrianHordyk/LBSPR#9]
The documentation indicates that `plotTarg` returns a ggplot object. 

However, `plotTarg` returns a dataframe, unlike LBSPR's other plot functions, 

Are the final lines of this function intentional? 

```
...
print(Plot)
return(invisible(longDat))
```

**Comment by AdrianHordyk** [comment]
Hey Andrew!
There was probably a reason for this at some stage, but I don't recall what it was. Doesn't seem necessary. 
Feel free to submit a PR if you like so it is consistent with the others.

**Comment by ahharvey** [comment]
Thanks Adrian!

PR submitted https://github.com/AdrianHordyk/LBSPR/pull/10

Are you still on your Murdoch email address? Have a couple of questions about the LBSPR method that I'd like to run past you.

**Comment by AdrianHordyk** [comment]
Great, merged. No Murdoch email isn't working anymore, best to email me at ar.hordyk@gmail.com
